### ISSUE TITLE
[Epic] Java: public preview

### ISSUE THREAD

**Issue by mikhailshilkov** [pulumi/pulumi-java#149]
Java as a new supported language in Pulumi SDKs.

### Design and specification 📔

- [x] [PR/FAQ: TODO](https://docs.google.com/document/d/1F7uAxUb7Otu5Kj3-5tbLe0O4tnDT7YrTYV5wBsXws8w/edit#)
- [x] [Brainstorming doc](https://docs.google.com/document/d/13LziCM6YOHJ_gxKetD1lznf1dwcmeJgzo9pAUQV0jI0/edit#heading=h.vq72q6weydu7)

### M68

- [x] Create a `pulumi-java` private repository, invite Paweł Prażak
- [x] Land the existing SDK prototype code in `pulumi-java`
- [x] Land the existing codegen prototype code in `pulumi-java`
- [x] https://github.com/pulumi/pulumi-java/issues/3
- [x] https://github.com/pulumi/pulumi-java/issues/5
- [x] https://github.com/pulumi/pulumi-java/issues/4
- [x] Review codegen Support for Java provider SDKs - it's working but buggy, we're upgrading and finding issues
- [x] Review Programgen Support for Java Expressions - it's basically missing
- [x] https://github.com/pulumi/pulumi-java/issues/38
- [x] https://github.com/pulumi/pulumi-java/issues/42
- [x] https://github.com/pulumi/pulumi-java/issues/43
- [x] https://github.com/pulumi/pulumi-java/issues/45
- [x] https://github.com/pulumi/pulumi-java/issues/46

### M69

- [x] https://github.com/pulumi/pulumi-java/issues/131  
- [x] https://github.com/pulumi/pulumi-java/issues/132   
- [x] https://github.com/pulumi/pulumi-java/issues/47    
- [x] https://github.com/pulumi/pulumi-java/issues/44
- [x] https://github.com/pulumi/pulumi-java/issues/72
- [x] https://github.com/pulumi/pulumi-java/issues/70
- [x] https://github.com/pulumi/pulumi-java/issues/68
- [x] https://github.com/pulumi/pulumi-java/issues/134   API design for required params
- [x] https://github.com/pulumi/pulumi-java/issues/135   Review mock testing

### M70 - private preview due

- [x] https://github.com/pulumi/pulumi-java/issues/69
- [x] https://github.com/pulumi/pulumi-java/issues/71
- [x] https://github.com/pulumi/pulumi-java/issues/185
- [x] https://github.com/pulumi/pulumi-java/issues/164
- [x] https://github.com/pulumi/pulumi-java/issues/199
- [x] https://github.com/pulumi/pulumi-java/issues/210
- [x] https://github.com/pulumi/pulumi-java/issues/205
- [x] https://github.com/pulumi/pulumi-java/issues/212
- [x] https://github.com/pulumi/pulumi-java/pull/184
- [x] https://github.com/pulumi/pulumi-java/issues/133   Compare API to CDK
- [x] https://github.com/pulumi/pulumi-java/issues/28    API design for I/O
- [x] #222 
- [x] #223 

### M71 - public preview due
- [x] https://github.com/pulumi/pulumi-java/issues/26    Clean up internal annotations
- [x] https://github.com/pulumi/pulumi-java/issues/73
- [x] https://github.com/pulumi/pulumi-jvm/issues/135
- [x] #224 
- [x] https://github.com/pulumi/pulumi-java/issues/1
- [x] #225 
- [x] https://github.com/pulumi/pulumi-jvm/issues/16
- [ ] https://github.com/pulumi/pulumi-jvm/issues/17
- [x] https://github.com/pulumi/pulumi-jvm/issues/353
- [x] #361

Packaging and publishing:
- [x] #347
- [x] #346

API changes:
- #366 
- [ ] https://github.com/pulumi/pulumi-java/issues/25    API design for optionals
- https://github.com/pulumi/pulumi-jvm/issues/243
- https://github.com/pulumi/pulumi-jvm/issues/237
- https://github.com/pulumi/pulumi-jvm/issues/226
- https://github.com/pulumi/pulumi-jvm/issues/29
- https://github.com/pulumi/pulumi-jvm/issues/138

Examples:

- [ ] Eject examples from pulumi-java to pulumi/examples
- should we add more? we have good candidates

Add providers:

- [x] #344
- [x] #345

Docs:

- https://github.com/pulumi/pulumi-java/issues/35
- https://github.com/pulumi/pulumi-jvm/issues/74
- https://github.com/pulumi/pulumi-jvm/issues/75
- https://github.com/pulumi/pulumi-jvm/issues/76
- https://github.com/pulumi/pulumi-jvm/issues/333
- https://github.com/pulumi/pulumi-jvm/issues/334
- https://github.com/pulumi/pulumi-jvm/issues/335
- [x] #362

Not doing:
- Javadoc publishing for the provider SDKs

CI:
- https://github.com/pulumi/pulumi-java/issues/10
- https://github.com/pulumi/pulumi-java/issues/21    CI check - critical

Publicity:
- Blog post
- https://github.com/pulumi/pulumi-jvm/issues/364

### Stretch/post-preview 

- [ ] Yaml projects can be ejected to Java
- [ ] tf2pulumi/arm2pulumi/kube2pulumi support for Java
- [ ] Mutli-lang components can be authored in Java

## Objective and Key Results

- **Objective:** Empower as Many Cloud Builders as Possible
  - **Key result:** Java language SDK public preivew
