### ISSUE TITLE
[Epic] Java SDK: GA

### ISSUE THREAD

**Issue by mikhailshilkov** [pulumi/pulumi-java#598]
## Overview

This issue is an "epic" tracking the list of issues to be completed before the Java SDK becomes generally available. Currently, this list is being built and should not be considered anywhere close to exhaustive. It will hold the issues that we know we need to address, but more issues will be added over time based on user feedback and other discoveries.

### M73 ⚙️

- [x] https://github.com/pulumi/pulumi-java/issues/583
- [x] https://github.com/pulumi/pulumi-java/issues/547
- [x] https://github.com/pulumi/pulumi-java/issues/419
- [x] https://github.com/pulumi/pulumi-java/issues/557
- [x] https://github.com/pulumi/pulumi-java/issues/627
- [x] https://github.com/pulumi/pulumi-java/issues/549
- [x] https://github.com/pulumi/pulumi-java/issues/420
- [x] https://github.com/pulumi/pulumi-java/issues/595
- [x] https://github.com/pulumi/pulumi-java/issues/549
- [x] https://github.com/pulumi/pulumi-java/issues/568
- [x] https://github.com/pulumi/pulumi-java/issues/529

### M74 ⚙️

- [x] https://github.com/pulumi/pulumi-java/issues/163
- [x] https://github.com/pulumi/pulumi-java/issues/548
- [x] https://github.com/pulumi/pulumi-java/issues/576
- [x] https://github.com/pulumi/pulumi-java/issues/478
- [x] https://github.com/pulumi/pulumi-java/issues/553

### M75 ⚙️

- [x] #82
- [x] #381
- [x] https://github.com/pulumi/pulumi-java/issues/640
- [x] #717
- [x] #731
- [x] #390
- [x] https://github.com/pulumi/pulumi-java/issues/739
- [x] https://github.com/pulumi/pulumi-java/issues/749
- [x] #594
- [x] #646

### M76

- [x] #702
- [x] #763
- [x] https://github.com/pulumi/pulumi-java/issues/694
- [x] https://github.com/pulumi/pulumi-java/issues/695
- [x] https://github.com/pulumi/pulumi-java/issues/702
- [x] https://github.com/pulumi/pulumi-java/issues/763
- [x] https://github.com/pulumi/pulumi-java/issues/774
- [x] https://github.com/pulumi/pulumi-java/issues/787

### M77

- [x] #643
- [x] #704 
- [x] https://github.com/pulumi/pulumi-java/issues/821 (@pawelprazak helping with this)

### Future
- [ ] https://github.com/pulumi/pulumi-java/issues/830 (blocks Providers team)
- [ ] #629
- [ ] https://github.com/pulumi/pulumi-java/issues/965

**Comment by pawelprazak** [comment]
I'm already working on this one:
https://github.com/pulumi/pulumi-java/issues/553

**Comment by pawelprazak** [comment]
I've written down the refactorings that I find beneficial to the project: https://github.com/pulumi/pulumi-java/issues/626
